package com.java8;

import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.Stream;

public class Prac {

    public static void main(String[] args) {


        List<Integer> list = Arrays.asList(10, 20, 40, 55, 6, 30, 140, 5,65);

        List<String> list1 = Arrays.asList("jak", "apple", "mahmood", "zahedi", "apple", "zahedi");
        List<String> list2 = Arrays.asList("apple", "samsung", "redmi", "oneplus", "motorola", "xiomi");

        List<Employee> emp = Arrays.asList(new Employee(1, "javed", 5000, "IT", 35),
                new Employee(2, "mahmood", 25000, "IT", 36),
                new Employee(3, "jaga", 10000, "HR", 39),
                new Employee(4, "balo", 50000, "HR", 34),
                new Employee(5, "soumen", 52000, "marketing", 40),
                new Employee(6, "sougata", 70000, "Railway", 42),
                new Employee(7, "deepak", 45000, "Railway", 36),
                new Employee(8, "sumanta", 35000, "Railway", 38));

        String str="hgtrfghhyruimn";

//        1. Arrays element count.........
//        2.list sort ascending order..........
//        3.list sort Descending order................
//        4.Unique and duplicate element in list.............
//        5.max and min.....................
//        6.find second-highest value from list........................
//        7.List sort based on String length............
//        8.Average sum...............
//        9.String non repeat character and occurrence..............
//        10.String repeat character and occurrence..........
//        10.sort employee based on age and name............
//        11.find name which age is highest............
//        12.find second-highest age in employee object.....
//        13.Counting Employee By Each Department...............
//        14.Department wise which age is highest and lowest..............
//        15.Department wise employee name which name starts with ..........
//        16.Department wise employee name which age is between ..........
//        17.Find Each Department sort employee based on age and which age is second highest...........
//        18.average age and sum of age by each department...............
//        19.find department name which has the highest age........
//        20.Find department name which has the highest number of employee.............

        // Department wise which age is highest and lowest..............

        Map<String,Optional<Employee>> map=emp.stream().collect(Collectors.groupingBy(Employee::getDepartment,Collectors.maxBy(Comparator.comparing(Employee::getAge))));

        map.forEach((k,v)->{
            System.out.println("Department..."+k+ " "+v.get().getName());

        });





    }

}