package com.java8;

public class Questions {
    //String str="hgtrfghhyruimn";

//        1. Arrays element count.........
//        2.list sort ascending order..........
//        3.list sort Descending order................
//        4.Unique and duplicate element in list.............
//        5.max and min.....................
//        6.find second-highest value from list........................
//        7.List sort based on String length............
//        8.Average sum...............
//        9.String non repeat character and position..............
//        10.String repeat character and occurrence..........
//        11.sort employee based on age and name............
//        12.find name which age is highest............
//        13.find second-highest age in employee object.....
//        14.Counting Employee By Each Department...............
//        15.Department wise which age is highest and lowest..............
//        16.Department wise employee name which name starts with ..........
//        17.Department wise employee name which age is between ..........
//        18.Find Each Department sort employee based on age and which age is second highest...........
//        19.average age and sum of age by each department...............
//        20.find department name which has the highest age........
//        21.Find department name which has the highest number of employee.............
//        22.Department wise which age is highest and lowest..............
//        23.String str="orange:1;apple:2;orange:5;pears:10";  output---orange-6,apple-2,pears=10
//        24.int[] nums=[1,1,1,2,2,2,3,3,3]                    output----[1,1,2,2,3,3]
//        25. int [] num=[1,3,4,1,3,5]                        output---[1,3,4,5] only unique showing
//        26. nums=[2,3,10,7,6]                                output--- check 2*3=6 next element is 6 or not 3*10=30 next element 30 0r not
//        27. int [] nums={2,4,7,64,32,9,16};             // finding the power of 2 each array element
//          28. Average Salary of IT Deoartment.........
}
